Console.Clear();
Console.WriteLine("Hello, Quandale Dingle!");
Console.WriteLine("Wazz Upppp");
Console.WriteLine("Yo mama!");
Console.WriteLine("Nahh bruv");
Console.WriteLine("Como te llamas me amigo?");
string namn = Console.ReadLine();
Console.WriteLine("Me llamo " + namn);
Console.WriteLine("Age check?");
string Ålder = Console.ReadLine();
Console.WriteLine("Dawg I'm " + Ålder);